{"name": "test_user_logins_with_employee_number_that_does_not_exist", "status": "passed", "description": "存在しない社員番号でログインできないことをテスト", "attachments": [{"name": "log", "source": "8bfc3030-dced-4ef8-a1d9-8e03c57b333f-attachment.txt", "type": "text/plain"}], "start": 1673748205013, "stop": 1673748205147, "uuid": "a7834130-679c-4d13-a69d-8c59daab4c98", "historyId": "e991bc953e6500305925bd2a2dd3df94", "testCaseId": "f4856b54813a7d9ac5a6c3db6e739508", "fullName": "application.tests.test_login.TestLoginUser#test_user_logins_with_employee_number_that_does_not_exist", "labels": [{"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "application.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestUserSerializer"}, {"name": "host", "value": "eab8ab219ba9"}, {"name": "thread", "value": "309-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "application.tests.test_login"}]}