{"name": "test_user_logins_with_incorrect_password", "status": "passed", "description": "間違ったパスワードでログインできないことをテスト", "attachments": [{"name": "log", "source": "1192b64d-bb8a-4478-8364-2f81c4f07875-attachment.txt", "type": "text/plain"}], "start": 1673748204641, "stop": 1673748204770, "uuid": "e6384d0a-ae5d-483e-89a8-0b03aa5d68d7", "historyId": "26348110a4196fcbd5f08975e358891b", "testCaseId": "9b3416738bf5851ad5b827acd9b2781b", "fullName": "application.tests.test_login.TestLoginUser#test_user_logins_with_incorrect_password", "labels": [{"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "application.tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestUserSerializer"}, {"name": "host", "value": "eab8ab219ba9"}, {"name": "thread", "value": "309-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "application.tests.test_login"}]}